### ISSUE TITLE
There is no class "ShellLinkHelper" found in latest version 1.0.6.2 from Maven Center

### ISSUE THREAD

**Issue by canglongxiang** [DmitriiShamrikov/mslinks#31] opened 2021-09-07 02:43 UTC
There is no class "ShellLinkHelper" found in latest version **1.0.6.2** from **Maven Center**. And it will use "ShellLinkHelper" class in README example.

**Comment by vatbub** [comment] 2021-09-07 06:20
Hey ☺️ Can you please tell me the compiler error that you get? What Java version are you using? And lastly, if you could copy-paste the code where you're calling mslinks, that would be great. Thanks 😎

**Comment by canglongxiang** [comment] 2021-09-07 07:06
Thanks for your reply.

I build my project with Maven(_com.github.vatbub:mslinks:**1.0.6.2**_), and try to use the same code as described in README.

> Easiest way to create link with default parameters: ShellLinkHelper.createLink("targetfile", "linkfile.lnk")

And "ShellLinkHelper" can not found in jar.

**Comment by vatbub** [comment] 2021-09-07 09:53
Oh, indeed, something went wrong there while merging branches. I will fix that once I get home today.

**Comment by DmitriiShamrikov** [comment] 2021-09-07 09:59
because it was added in 1.0.7

**Comment by vatbub** [comment] 2021-09-07 10:07
Oh, that explains it 🙈

**Comment by canglongxiang** [comment] 2021-11-09 10:08
So, when deploy v1.0.7 to Maven Center? It still only can be get latest version 1.0.6.2...

**Comment by vatbub** [comment] 2021-11-10 00:35
Hi :) Yeah, I didn't get around publishing v1.0.7 on maven central and I probably won't have time in the near future to do so. However, feel free to do it yourself. Here's what you need to do:

1. Fork my fork (https://github.com/vatbub/mslinks)
2. Merge the master branch of this repo into your fork
3. Run `mvn clean verify` and fix any errors/problems (this is the time consuming step)
4. Configure maven for uploading to Maven Central (This may also take some time in case you have never published to Maven Central; [Official guide](https://maven.apache.org/repository/guide-central-repository-upload.html))
5. Publish it using `mvn release:prepare release:perform`

In case you need help, feel free to contact me (probably by creating an issue in my fork). However, I cannot promise you I will have time to help you.
Cheers :)

**Comment by DmitriiShamrikov** [comment] 2022-01-01 16:27
duplicate of #29

**Closed by DmitriiShamrikov** 2022-01-01 16:27 UTC
