### ISSUE TITLE
ItemID type 46 (0x2E)

### ISSUE THREAD

**Issue by alexturc** [DmitriiShamrikov/mslinks#13] opened 2018-02-27 00:29 UTC
Hi,
I get this Exception:

mslinks.ShellLinkException: unsupported ItemID type
	at mslinks.data.ItemID.<init>(ItemID.java:144)
	at mslinks.LinkTargetIDList.<init>(LinkTargetIDList.java:71)
	at mslinks.ShellLink.<init>(ShellLink.java:113)
	at mslinks.ShellLink.<init>(ShellLink.java:105)

This happens on Windows 10.
I created a directory shortcut using the context menu option. It's very simple shortcut.
I remember this used to work just fine when I started using the library. I'm wondering if something changed with the latest Windows updates.

Thanks,
Alex.

**Comment by BlackOverlord666** [comment] 2018-02-27 04:38
Ok, i'll investigate this soon

**Comment by BlackOverlord666** [comment] 2018-03-03 21:33
I've tried it just now and it worked as expected. I have Windows 10 Pro 1709 (build 16299.248) and used following code:
```java
ShellLink sl = new ShellLink("win10.shortcut.lnk");
System.out.println( sl.resolveTarget() );
```

Can you explain in detail what are you doing and attach your .lnk file?

**Comment by mrekin** [comment] 2018-09-26 11:08
Hi!
I have the same problem (ItemID type 46).
Win 10 1803, build 17134.286 ,  mslinks lib version 1.0.4. Primary lang is Russian (may be it will help)
Seems that problem exist if target file located some where in 
C:\Users\
(tested with Documents/Images folders, like _C:\Users\xam\Documents\test_
All works fine  in other cases.

**Comment by BlackOverlord666** [comment] 2018-12-15 16:37
Hi! It seems like creating link file through Create Shortcut window (right click/New/Shortcut) is different from creating one using drag-n-drop menu. In the first case Windows may create path with references to well known system directories (Desktop, Documents, Downloads, etc). Due to lack of documentation, I don't know how exactly this references works and stored, thus it is not implemented as I mentioned in readme.

I will appreciate PR if someone willing to do some research about this undocumented part of the format.

**Comment by ctwist** [comment] 2019-08-14 04:09
I have not found any documentation about this type of shortcut, but this is what I have worked out.

Type 46 refers to a link that was created in the user's documents folder. The path in the link excludes "C:\Users\username\Documents". If you view the link's properties, the full path is shown, but Windows dynamically adds the high-level portion of the path. I assume that this is intended to make the link portable if you change the location of your documents folder.

I wanted to attach a sample link, but .lnk files cannot be attached and if I try to zip it, it includes the link target but not the link. However you can easily create a link as described above.

I have a working "dirty" version that supports this type of link, you will want to adapt this to your coding techniques. This is what I changed:

- ItemID
Add:
`public static final int TYPE_DOCUMENTS_DIRECTORY = 0x2e;`
Process TYPE_DOCUMENTS_DIRECTORY the same as TYPE_DIRECTORY.
- ShellLink.resolveTarget()
In the for loop, add
`else if (i.getType() == ItemID.TYPE_DOCUMENTS_DIRECTORY) {
	JFileChooser fc = new JFileChooser();
	FileSystemView fw = fc.getFileSystemView();
	path += fw.getDefaultDirectory() + i.getName().substring(7) + File.separator;
}
`
This removes 7 bytes of extra data from the beginning of the path, and adds the path of the documents folder to the beginning of the path.

That's all. The link is now processed correctly.

**Comment by mrekin** [comment] 2019-08-14 05:40
**ctwist**
Thanks for a solution.
Anyway, 
Using `JFileChooser fc = new JFileChooser()`
not the best solution: `new JFileChooser()` can be extremely slow (up to 20 sec in some cases).
I think better to use `user.home` property or something like this.

**Comment by ctwist** [comment] 2019-08-14 14:37
user.home doesn't work because the documents folder is not always in the home directory. E.g. on my tablet which has limited storage, the documents folder is on the SD card. I couldn't find a suitable Java variable for the documents folder.

Here is a more efficient solution without JFileChooser.
`FileSystemView fv = FileSystemView.getFileSystemView();`

**Comment by vatbub** [comment] 2019-08-14 18:57
I hope you guys don't mind me adding my opinion on the matter 😉

I also agree that we shouldn't use any AWT, Swing or JavaFX methods in non-UI-code. 

I therefore googled around a little and found [this question](https://stackoverflow.com/questions/9677692/getting-my-documents-path-in-java) on StackOverflow and think that the answer marked as the solution doesn't look too bad.

**Comment by DmitriiShamrikov** [comment] 2019-08-24 13:08
I'm not sure what is worse - using ui classes here or running external processes 😊

Furthermore, it's not enough to implement this kind of workarounds to get paths for some well know directories such as Documents to cover most of the cases.

0x2e is a type of ItemID (like the others - drive, file, directory, etc) and actual reference to directory is described following in the data stream. So that 0x2e is not necessary means Documents directory. It can be Desktop or Downloads etc, depending on the following bytes.

I would call it something like:
`public static final int TYPE_SYSTEM_DIRECTORY = 0x2e;`

But the problem is that I don't know how to read the following data. We need more reverse engineering here. Unfortunately, I don't have time for this for now.

**Comment by DmitriiShamrikov** [comment] 2022-06-27 21:25
The support for special folders (including Documents) has been added in 1.1.0. See readme for more details

**Closed by DmitriiShamrikov** 2022-06-27 21:25 UTC
